CREATE DATABASE MINIPJ;
drop DATABASE if EXISTS MINIPJ;
use MINIPJ;

CREATE table SYMBOL(SYMBOLID int AUTO_INCREMENT, SYMBOLname VARCHAR(20) not NULL, IMGPATH VARCHAR(255), 
                    constraint PRIMARY KEY(SYMBOLID));

CREATE TABLE CATEGORY (
    CATEGORYID INT PRIMARY KEY AUTO_INCREMENT,
    CATEGORYname VARCHAR(20) NOT NULL
);
CREATE TABLE MATERIAL (
    MATERIALID INT AUTO_INCREMENT PRIMARY KEY,
    MATERIALname VARCHAR(50) NOT NULL,
    MATERIALguide VARCHAR(255)
);

CREATE TABLE CLOTHES(
    CLOTHESID INT PRIMARY KEY AUTO_INCREMENT,
    CLOTHESname VARCHAR(100) NOT NULL,
    CATEGORYID INT, CONSTRAINT FOREIGN KEY (CATEGORYID) REFERENCES CATEGORY(CATEGORYID),
    MATERIALID INT, CONSTRAINT FOREIGN KEY (MATERIALID) REFERENCES MATERIAL(MATERIALID),
    IMGPATH VARCHAR(255) 
);

CREATE TABLE DRY (
    DRYID INT AUTO_INCREMENT PRIMARY KEY,
    DRYguide VARCHAR(50) NOT NULL,
    methode VARCHAR(255) NOT NULL,
    advantage VARCHAR(255),
    caution VARCHAR(255)
);
SHOW TABLES

CREATE TABLE CLOTHESSYMBOLLIST (
    CLOTHESID INT,
    SYMBOLID INT,

    CONSTRAINT FOREIGN KEY (CLOTHESID) REFERENCES CLOTHES(CLOTHESID),
     CONSTRAINT FOREIGN KEY (SYMBOLID) REFERENCES SYMBOL(SYMBOLID)
);

CREATE TABLE CLOTHESDRYINGLIST(
    CLOTHESID INT,
    DRYID INT,

    CONSTRAINT FOREIGN KEY (CLOTHESID) REFERENCES CLOTHES(CLOTHESID),
    CONSTRAINT FOREIGN KEY (DRYID) REFERENCES DRY(DRYID)
);